apiVersion: v2
name: kepler
description: A Helm chart for Kepler - Kubernetes Efficient Power Level Exporter
icon: https://avatars.githubusercontent.com/u/91567619?s=200&v=4
home: https://sustainable-computing.io/
sources:
  - https://github.com/sustainable-computing-io/kepler
maintainers:
  - name: Kepler Team
    url: https://github.com/sustainable-computing-io/kepler
keywords:
  - energy
  - power
  - monitoring
  - prometheus
  - sustainability
  - cloud-native
  - sustainable-computing
annotations:
  category: Monitoring
  artifacthub.io/links: |
    - name: support
      url: https://github.com/sustainable-computing-io/kepler/issues/new
    - name: docs
      url: https://sustainable-computing.io/
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: [GPG_KEY_FINGERPRINT]
    url: https://keybase.io/[MAINTAINER]/pgp_keys.asc
type: application
version: 0.0.0-dev
appVersion: latest
