# Default values for kepler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Repository to pull the image from
  repository: quay.io/sustainable_computing_io/kepler
  # -- Image tag, if empty it will get it from the chart's appVersion
  tag: ""
  # -- Pull policy
  pullPolicy: IfNotPresent

# -- Replaces the name of the chart in the Chart.yaml file
nameOverride: ""
# -- Replaces the generated name
fullnameOverride: ""

# -- Additional labels to add to all resources
labels: {}

# -- Additional annotations to add to all resources
annotations: {}

namespace:
  create: false
  name: kepler

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  name: kepler

rbac:
  # Specifies whether rbac should be created
  create: true

service:
  type: ClusterIP
  port: 28282
  targetPort: http
  protocol: TCP

daemonset:
  # -- Privileges and access control settings for a container
  securityContext:
    privileged: true
  # -- Node selection constraint
  nodeSelector:
    kubernetes.io/os: linux
  # -- Toleration for taints
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
    - operator: Exists # Tolerate all taints
  # -- Affinity rules
  affinity: {}
  # -- CPU/MEM resources
  resources: {}
  livenessProbe:
    httpGet:
      path: /metrics
      port: http
    initialDelaySeconds: 10
    periodSeconds: 60
  readinessProbe: {}

config:
  log:
    level: debug
    format: text
  host:
    sysfs: /host/sys
    procfs: /host/proc
  monitor:
    interval: 5s
    staleness: 500ms
    maxTerminated: 100
    minTerminatedEnergyThreshold: 10
  rapl:
    zones: []
  exporter:
    stdout:
      enabled: false
    prometheus:
      enabled: true
      debugCollectors:
        - go
  web:
    configFile: ""
    listenAddresses:
      - :28282
  debug:
    pprof:
      enabled: false
  kube:
    enabled: false
    config: ""
    nodeName: ""
  dev:
    fake-cpu-meter:
      enabled: false
      zones: []

serviceMonitor:
  enabled: false
  interval: 30s
  path: /metrics
  labels: {}
  annotations: {}

networkPolicy:
  enabled: false
  egress: {}
  ingress:
    - ports:
        - protocol: TCP
          port: 28282
