log:
  level: debug
  format: text

exporter:
  mcp:
    enabled: true
    transport: "sse" # Server-Sent Events transport
    httpPath: "/mcp" # HTTP endpoint path
  prometheus:
    enabled: true

web:
  listenAddresses:
    - ":28282"

dev:
  fake-cpu-meter:
    enabled: false
    zones: ["package", "core", "uncore", "dram"]
